# docker-compose.yml
version: '3'
services:

# Nginx
  nginx:
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - target-service
      - read-service
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M  
# RabbitMQ      
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672  
    networks:
      - default
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 500M
# MongoDB
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    networks:
      - default
    volumes:
      - ./mongodb/data:/data/db
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M

###########################################
### Micro Services ########################
###########################################

# Target service
  target-service:
    build: ./target-service
    ports:
      - 3001:3001
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - default
    volumes:
      - ./target-service:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./envFiles/target-service.env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M 

# Read service
  read-service:
    build: ./read-service
    ports:
      - 3006:3006
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - default
    volumes:
      - ./read-service:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./envFiles/read-service.env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
    
# Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/prometheus-data:/prometheus
    depends_on:
      - target-service
      - read-service
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

  db-exporter:
    image: bitnami/mongodb-exporter:latest
    ports:
      - 9216:9216
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
    depends_on:
      - mongodb

# Grafana
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    ports:
      - 3008:3000
    volumes:
       - grafana-data:/var/lib/grafana
    networks:
      - default

# Network
networks:
  default:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: